[package]
name = "reborn_program"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread", "time"] }
iced = "0.6.0"
lazy_static = "1.4.0"
sha256 = "1.0.3"
serde_json = "1.0"
reqwest = "0.11"
base64 = "0.20.0"
image-base64 = "0.1.0"